version: '3'

services:
  db:
    image: mongo
    ports: 
      - "27017:27017"
  api:
    build: .
    environment:
      - APP_PORT=3000
    command: bash -c "npm install --silent && npm run build && npm run dev"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db