version: '3'

services:
  db:
    image: mongo
  api:
    build: .
    environment:
      - APP_PORT=8080
    command: bash -c "npm install && npm run build && npm run dev"
    volumes:
      - .:/app
    ports:
      - "3000:8080"
    depends_on:
      - db