version: '3'

services:
  db:
    image: mongo
    ports: 
      - "27017:27017"
  api:
    build: .
    environment:
      - APP_PORT=80
    command: bash -c "npm install && npm run build && npm start"
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
